### ISSUE TITLE
Is there a plan to release the data generation process code?

### ISSUE THREAD

**Issue by zhuqiangLu** [Galaxies99/TransCG#1]
Hi there,

At first, thank you for your excellent work. Recently I am trying to get my own data for the transparent object. In fact, I am particularly interest in getting the 3D model for a transparent object using a turn table. So are you going to release the code for data gathering process?

Best Regard

**Comment by Galaxies99** [comment]
Hello! First, thank you for your interest in our work.

Since it will take some time to organize the collection code, we may release the data collection code a few months later.

As for the 3D model scanning process, we use the opaque material (e.g., colored tin paper) to cover the surface of the transparent object. Then we can use the traditional scanner to scan the 3D model of transparent objects.

**Comment by Gaben21** [comment]
您好，请问您是否可以提供数据集制作的相关代码呢？感谢！
